name: CI pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to test
        uses: lwitkowski/playground-deploy-action@master
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          gitops-repo: 'lwitkowski/playground-gitops'
          target-file: 'sample-service/test/values.yaml'

      - name: Deploy to production
        uses: lwitkowski/playground-deploy-action@master
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          gitops-repo: 'lwitkowski/playground-gitops'
          target-file: 'sample-service/prod/values.yaml'
          docker-image-tag: ${GITHUB_SHA::6}