name: CI pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY_GITOPS_REPO: 'lwitkowski/playground-gitops'
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
      - name: Deploy to test
        uses: lwitkowski/gitops-deploy-tag-action@master
        with:
          target-file: 'sample-service/test/values.yaml'

      - name: Deploy to production
        uses: lwitkowski/gitops-deploy-tag-action@master
        with:
          target-file: 'sample-service/prod/values.yaml'